extends:
  # - '@commitlint/config-lerna-scopes'
  - '@commitlint/config-conventional'
rules:
  header-max-length: [1, 'always', 90]
  type-enum:
    - 2
    - always
    - - build
      - ci
      - docs
      - feat
      - fix
      - perf
      - refactor
      - style
      - test
      - revert

  # Decide the scopes to use for projects
  # scope-enum:
  #   - 2
  #   - always
  #   - - 
help: |
  **Possible types**:
  `build`:            Change build process, tooling or dependencies.
  `ci`:               Changes to our CI configuration files and scripts
  `docs`:             Adds or alters documentation.
  `feat`:             Adds a new feature.
  `fix`:              Solves a bug.
  `perf`:             Improves performance.
  `refactor`:         Rewrites code without feature, performance or bug changes.
  `style`:            Improves formatting, white-space.
  `test`:             Adds or modifies tests.
  `revert`:           Changes that reverting other changes/commits
