name: CI

on:
  push:
    branches: main
  pull_request:
    branches: [main, master]
    types: [opened, reopened, labeled, synchronize]
  workflow_dispatch:
    
permissions:
  pull-requests: write
  contents: write
  issues: write
  
jobs:
  Sonar-Analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo Data
        uses: actions/checkout@v3
        
      - name: SonarCloud Analysis
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKENIZED }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=Majikjack620_senior-project
            -Dsonar.organization=majikjack620
            
  Dependabot-PR-Assigner:
    runs-on: ubuntu-latest
    if: ${{github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'}}
    steps:
      - name: Assign PR to Reviewer
        uses: pozil/auto-assign-issue@v1
        with:
          repo-token: ${{secrets.TOKENIZED}}
          assignees: Majikjack620
          numOfAssignee: 1
          allowSelfAssign: true
          
  Dependency-Validator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo Data
        uses: actions/checkout@v3
        
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: "14"
          
      - name: Upgrade npm
        run: npm i -g npm@7
        
      - name: Check for outdated dependencies
        run: |
          cd backend
          npm i
          npm outdated
          npm outdated >> update.txt
      
      - name: Save file
        uses: actions/upload-artifact@v3
        with:
          name: updateThese
          path: output.txt
        


      
