name: CI

on:
  push:
    branches: main
    
permissions:
  pull-requests: read
  contents: read
  issues: read

jobs:       
    Semantic-Release:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repo
          uses: actions/checkout@v3

        - name: Semantic Release
          uses: cycjimmy/semantic-release-action@v3
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
