name: CI

on:
  push:
    branches: main
  pull_request:
    branches: [main, master]
    types: [opened, reopened, labeled, synchronize]
  workflow_dispatch:
    
permissions:
  pull-requests: write
  contents: write
  issues: write
  
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo Data
        uses: actions/checkout@v3
          
#       GITHUB ACTION FOR DEPENDENCY CHECKER. NOT WORKING CURRENTLY, ONLY RECOGNIZES WHEN DEPENDENCIES ARE CHANGED FROM ANOTHER SOURCE
#       - if: ${{ github.event_name == 'pull_request' }}
#         name: Dependency Check
#         uses: actions/dependency-review-action@v3.0.6
          
      
      - if: ${{ github.event_name == 'pull_request' }}
        name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: "14"
          
      - if: ${{ github.event_name == 'pull_request' }}
        name: Upgrade npm
        run: npm install -g npm@7
        
      - if: ${{ github.event_name == 'pull_request' }}  
        name: Check for outdated dependencies
        run: cd /home/runner/work/senior-project/backend && npm install
        
        
      - name: SonarCloud Analysis
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKENIZED }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=Majikjack620_senior-project
            -Dsonar.organization=majikjack620
          
      - if: ${{github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'}}
        name: Assign PR to Reviewer
        uses: pozil/auto-assign-issue@v1
        with:
          repo-token: ${{secrets.TOKENIZED}}
          assignees: Majikjack620
          numOfAssignee: 1
          allowSelfAssign: true
